#!/usr/bin/env python

import sys
import os

from setuptools import Distribution
from setuptools.command.build_ext import build_ext

def main():
    names = sys.argv[1:]
    if not names:
        cmd = os.path.splitext(os.path.basename(sys.argv[0]))[0]
        print(f"usage: {cmd} NAME...", file=sys.stderr)
        sys.exit(2)

    cmd = build_ext(Distribution())
    for name in names:
        print(cmd.get_ext_filename(name))

if __name__ == "__main__":
    main()
